import { NextFontWithVariable } from "next/dist/compiled/@next/font"
import { Open_Sans } from "next/font/google"
import { config } from "@fortawesome/fontawesome-svg-core"
import "@/styles/globals.css"

config.autoAddCss = false

const open_sans: NextFontWithVariable = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans"
})

const default_style: string =
  "m-0 font-sans antialiased font-normal text-left leading-default text-base dark:bg-slate-950 bg-gray-50 text-slate-500 dark:text-white"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" className={`${open_sans.variable}`}>
      <body className={default_style}>{children}</body>
    </html>
  )
}

export default RootLayout
